spring:
  application:
   name: api-gateway

server:
  port: 8762

#api
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
           - path
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka