spring.application.name=order-service
server.port=9011
#db
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.name=velocious
spring.datasource.password=Avaali1$
spring.jpa.hibernate.ddl-auto=create
#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
