spring.application.name=cart-service

server.port=9014

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/cartDB
spring.datasource.username=postgres
spring.datasource.name=velocious
spring.datasource.password=Avaali1$
spring.jpa.hibernate.ddl-auto=update


#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=2
spring.data.redis.timeout=2000ms
spring.data.redis.connect-timeout=2000ms
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=1000ms
spring.data.redis.lettuce.shutdown-timeout=200ms
